server:
  port: 9080
spring:
  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 12345
    driver-class-name: com.mysql.jdbc.Driver

#SpringBoot整合Mybatis配置
mybatis:
  type-aliases-package: com.szjt.reactservice
  mapper-locations: classpath:/mappers/*.xml